### ISSUE TITLE
Cashfree misbehaving with other Payment plugins in woocommerce

### ISSUE THREAD

**Issue by shivsah** [cashfree/cashfree-woocommerce#15]
Cashfree new update is misbehaving with other payment plugins, rendering the payments tab in woocommerce unusable, and no checkout options are showing up on the final checkout page.

Here's an error for your reference.
`An error of type E_ERROR was caused in line 51 of the file /home/somewebsite.com/public_html/wp-content/plugins/woocommerce/src/Internal/Utilities/HtmlSanitizer.php. Error message: Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\Internal\Utilities\HtmlSanitizer::sanitize() must be of the type string, null given, called in /home/somewebsite.com/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 308 and defined in /home/somewebsite.com/public_html/wp-content/plugins/woocommerce/src/Internal/Utilities/HtmlSanitizer.php:51
Stack trace:
#0 /home/somewebsite.com/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php(308): Automattic\WooCommerce\Internal\Utilities\HtmlSanitizer->sanitize()
#1 /home/somewebsite.com/public_html/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php(163): WC_Payment_Gateway->get_title()
#2 /home/somewebsite.com/public_html/wp-includes/class-wp-hook.php(307): WC_Settings_Payment_Gateways->payment_gateways_setting()
#3 /home/somewebsite.com/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /home/somewebsite.com
`

**Comment by shivsah** [comment]
also whoever removed the transaction id from the order notes in woocommerce needs to add it back that was the best feature.

**Comment by prem-cashfree** [comment]
@shivsah It seems that one of your plugin is calling  `sanitize() ` method with `null` value. As cashfree plugin is not using `sanitize() ` method at all. So check with the others plugin. Or in case if you are still unable to use cashfree plugin try to reach techsupport@cashfree.com
