### ISSUE TITLE
Can you make a cashfree plugin for Paid Memberships Pro

### ISSUE THREAD

**Issue by bajpangosh** [cashfree/cashfree-woocommerce#2]
There is a lot of wordpress users use Paid Memberships Pro for Paid Memberships, I kindly request can you make a plugin for Paid Memberships Pro Payment Gateway there is a paytm plugin available but i don't have paytm  account i have cashfree account but there is no cash free payment gateway plugin for Paid Memberships Pro! 
here is the example https://github.com/strangerstudios/pmpro-example-gateway

same clone https://wordpress.org/plugins/pmpro-paytm-gateway/ 

can you make one for us.

**Comment by prem-cashfree** [comment]
@bajpangosh  But you can use this plugin for paid membership too. Just go to latest [release](https://github.com/cashfree/cashfree-woocommerce/releases/tag/v4.3.1) and download that.
